components:
  parameters:
    # Path Parameters
    TenantIdParam:
      name: tenantId
      in: path
      required: true
      description: Tenant identifier
      schema:
        type: string
        format: uuid

    UserIdParam:
      name: userId
      in: path
      required: true
      description: User identifier
      schema:
        type: string
        format: uuid

    DocumentIdParam:
      name: documentId
      in: path
      required: true
      description: Document identifier
      schema:
        type: string
        format: uuid

    UploadIdParam:
      name: uploadId
      in: path
      required: true
      description: Upload identifier
      schema:
        type: string
        format: uuid

    LinkIdParam:
      name: linkId
      in: path
      required: true
      description: Social link identifier
      schema:
        type: string
        format: uuid

    SessionIdParam:
      name: sessionId
      in: path
      required: true
      description: Chat session identifier
      schema:
        type: string
        format: uuid

    # Query Parameters
    PageParam:
      name: page
      in: query
      description: Page number for pagination
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1

    LimitParam:
      name: limit
      in: query
      description: Number of items per page
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20

    # Header Parameters
    AuthorizationHeader:
      name: Authorization
      in: header
      required: true
      description: JWT Bearer token
      schema:
        type: string
        pattern: '^Bearer .+$'

    ContentTypeHeader:
      name: Content-Type
      in: header
      required: true
      description: Content type of the request body
      schema:
        type: string
        enum:
          - application/json
          - multipart/form-data

    AcceptHeader:
      name: Accept
      in: header
      required: false
      description: Expected response format
      schema:
        type: string
        enum:
          - application/json
          - text/event-stream